import express from "express";import bcrypt from "bcryptjs";import jwt from "jsonwebtoken";import crypto from "crypto";import User from "../models/User.js";import Activity from "../models/Activity.js";import {requireAuth,requireRole} from "../middleware/auth.js";
const r=express.Router();const emailRe=/^[^\s@]+@[^\s@]+\.[^\s@]+$/;const cookieOptions=()=>({httpOnly:true,sameSite:"lax",secure:process.env.NODE_ENV==="production",maxAge:7*24*60*60*1000,path:"/"});
function token(u){return jwt.sign({sub:u._id.toString(),role:u.role},process.env.JWT_SECRET,{algorithm:"HS256",expiresIn:process.env.JWT_EXPIRES_IN||"7d"})}
function safe(u){return {id:u._id,name:u.name,email:u.email,role:u.role,organization:u.organization,department:u.department,language:u.language}}
r.post("/register",async(req,res)=>{const name=String(req.body.name||"").trim(),email=String(req.body.email||"").trim().toLowerCase(),password=String(req.body.password||""),confirm=String(req.body.confirmPassword||""),requested=String(req.body.role||"VIEWER").toUpperCase(),setup=String(req.body.setupKey||"");if(name.length<2||!emailRe.test(email)||password.length<10||password!==confirm)return res.status(400).json({message:"Enter valid details. Password must be at least 10 characters."});if(!["ANALYST","VIEWER","ADMIN"].includes(requested))return res.status(400).json({message:"Invalid role."});const count=await User.countDocuments();let role=requested;if(requested==="ADMIN"&&!(count===0&&setup&&setup===process.env.SETUP_ADMIN_KEY))return res.status(403).json({message:"Admin registration is available only during first-time setup with the configured setup key."});if(count>0&&requested!=="ADMIN")role=requested;if(await User.exists({email}))return res.status(409).json({message:"An account with this email already exists."});const u=await User.create({name,email,passwordHash:await bcrypt.hash(password,12),role,organization:String(req.body.organization||"CyberGuard").trim().slice(0,100),department:String(req.body.department||"Security").trim().slice(0,100)});await Activity.create({userId:u._id,action:"Account created",resource:"CyberGuard account"});res.status(201).json({message:"Account created. You can now sign in.",user:safe(u)})});
r.post("/login",async(req,res)=>{const email=String(req.body.email||"").trim().toLowerCase(),password=String(req.body.password||"");if(!emailRe.test(email)||!password)return res.status(400).json({message:"Enter a valid email and password."});const u=await User.findOne({email});const ok=u&&u.isActive&&await bcrypt.compare(password,u.passwordHash);if(!ok)return res.status(401).json({message:"Invalid email or password."});u.lastLoginAt=new Date();await u.save();await Activity.create({userId:u._id,action:"Signed in",resource:"CyberGuard account"});res.cookie("cg_token",token(u),cookieOptions()).json({user:safe(u)})});
r.post("/logout",requireAuth,async(req,res)=>{await Activity.create({userId:req.user._id,action:"Signed out",resource:"CyberGuard account"});res.clearCookie("cg_token",{httpOnly:true,sameSite:"lax",secure:process.env.NODE_ENV==="production",path:"/"});res.json({message:"Signed out"})});
r.get("/me",requireAuth,(req,res)=>res.json({user:req.user}));
r.patch("/profile",requireAuth,async(req,res)=>{const u=await User.findById(req.user._id);if(req.body.name)u.name=String(req.body.name).trim().slice(0,80);if(req.body.language&&["en","es","fr","de","ja","hi"].includes(req.body.language))u.language=req.body.language;await u.save();res.json({user:safe(u)})});
// Admin creates users; no seed data is used.
r.post("/admin-create",requireAuth,requireRole("ADMIN"),async(req,res)=>{const name=String(req.body.name||"").trim(),email=String(req.body.email||"").trim().toLowerCase(),password=String(req.body.password||""),role=String(req.body.role||"VIEWER").toUpperCase();if(name.length<2||!emailRe.test(email)||password.length<10||!["ADMIN","ANALYST","VIEWER"].includes(role))return res.status(400).json({message:"Provide a valid name, email, password (10+ chars), and role."});if(await User.exists({email}))return res.status(409).json({message:"Email already exists."});const u=await User.create({name,email,passwordHash:await bcrypt.hash(password,12),role});await Activity.create({userId:req.user._id,action:"Created user",resource:email});res.status(201).json({user:safe(u)})});
export default r;
